### ISSUE TITLE
Server Version=v0.15.0 Revision=d206d65 doesn't run

### ISSUE THREAD

**Issue by kseistrup** [noborus/ovcs#44]
[ Ref.: d206d655f0b3eb04565844658df03031c597e463 ]

Cloning the git repo and running `make build` compiles without any errors and produces a seemingly normal executable. However, `ovcs server` just exits. No reason is given, and the exit code is 0. When run with `--debug` the exit code is 1, but no messages are seen at all.

On the very first run, a very short “blink” can be seen in the terminal emulator, _as if_ some initialization occurs (but this is just guessing).

The binary can show a help page, produce shell completions, and stuff, but the `server` command fails.

Updating `github.com/noborus/ov` to `v0.33.3` in `go.mod` produces a similar result (different binary, identical behaviour).

The source of the v0.15.0 release also builds cleanly (I cannt say `make build` as it is no longer run in a git repo, but I can run the same command where I fill in the Version and Revision manually) — and `ovcs server` runs as expected.

The pre-compiled v0.15.0 release binary also runs as expected.

```sh
» uname -om
x86_64 GNU/Linux
» go version
go version go1.22.0 linux/amd64
» echo $GOFLAGS
-buildmode=pie -trimpath -ldflags=-linkmode=external -mod=readonly -modcacherw
» echo $LC_ALL
en_DK.UTF-8  # LC_ALL=C.UTF-8 produces same result
» echo $LANG
en_DK.UTF-8  # LANG=C.UTF-8 produces same result
» echo $TERM
xterm-256color
```

**Comment by kseistrup** [comment]
PS: Compiling `ovcs` from the stable v0.15.0 release (from last year) and using that one for `ovcs server`, works well with the `ovcs client` compiled from the latest commit (mentioned at the top of this post).

**Comment by noborus** [comment]
sorry. This is caused by ov https://github.com/noborus/ov/pull/489, so update to 0.33.3.

**Comment by kseistrup** [comment]
> This is caused by ov https://github.com/noborus/ov/pull/489, so update to 0.33.3.

I'm sorry, but I have to disagree: I already tried to update `ov` to v0.33.3 in `go.mod` before posting the issue, it didn't help.

Also, building from the latest commit (7efcf3cfea826a91bfd3c34aefed8e5e1bc440b5) still has the same problem as originally reported.

**Comment by kseistrup** [comment]
> I'm sorry, but I have to disagree

I'm sorry, false alarm: everything works perfectly. :+1:

For the records, in case someone else runs into the same problem:

My disagreement was caused by a “stale” `$XDG_CONFIG_HOME/ov/config.yaml` configuration file. Upgrading to `ovcs/0.16.0` and `ov/0.33.3` and using the `ov.yaml` configuration file that came with the latter solved the problem.

Thank you for your patience. :pray:

**Comment by noborus** [comment]
sorry. There was some confusion in the configuration file.

Additionally, there was a problem with the processing when the program terminated abnormally.
I will fix the cleanup on abnormal termination.
