### ISSUE TITLE
`ovcs` expects `ov` config in `$HOME/.ov.yaml`, but oviewer's config has moved

### ISSUE THREAD

**Issue by kseistrup** [noborus/ovcs#45]
[ Ref.: d206d655f0b3eb04565844658df03031c597e463 ]

`ov version 0.33.3 rev:8c70587` (and I believe also some earlier versions) is now looking for its configuration file in `$XDG_CONFIG_HOME/ov/config.yaml`. However, `ovcs` is still expecting it to be in a previously used location: `$HOME/.ov.yaml`

**Comment by noborus** [comment]
thank you. Only the help message was not updated.
