### ISSUE TITLE
[FYI] Available from ArchLinux User Repository (AUR) as `ovcs-git`

### ISSUE THREAD

**Issue by kseistrup** [noborus/ovcs#46]
This is just an informational message that can be closed at your descretion — no action is necessary.

ArchLinux users can now install `ovcs` directly from AUR: `ovcs-git`

+ https://aur.archlinux.org/packages/ovcs-git

It will compile a binary from the latest git commit and install it along with the README, LICENSE, and shell completions.

[The binary will not currently be able to serve, due to #44, but I assume that will be solved at some point.]

**Comment by noborus** [comment]
thank you. Add to README.md.
